### ISSUE TITLE
Frontmatter中设置单篇文章的license内容均被hugo.yaml内默认作者设置覆盖

### ISSUE THREAD

**Issue by h2dcc** [tom2almighty/hugo-narrow#24]
如题，在文中设置frontmatter的License信息后，被hugo.yaml中author设置覆盖。

```
---
showLicense: true
# 自定义版权信息（可选）
license:
  author: ABC
  name: "COPYRIGHT"
  link: "https://ABC.com"
---
```
